### ISSUE TITLE
Q&A feature issues

### ISSUE THREAD

**Issue by M0les** [venueless/venueless#180] opened 2021-01-25 06:33 UTC
Sorry, this is one of those vague "I saw this thing once" issues.

Anyway we've been trying out the Q&A tab feature for presentation rooms for LCA2021 online.

Some weirdnesses observed:
* Took a close/relaunch to enable Q&A tab editing for me as a moderator
* I can't see who asked a question and when, nor anything about the voting process other than the up count (Possibly privacy issues there, I guess). Everything in the main chat tab has this info.
* In one room, a question came in a long time after it must have been asked (Related to a presentation in the room ~1/2hr prior)
* After another reload, I lost the ability to mod/delete questions (But still another old question came in)

**Comment by raphaelm** [comment] 2021-12-19 16:23
I'm closing this for now since it's not reproducible, is a year old and we re-implemented the whole moderator part since then, so it might no longer apply at all.

The only thing in here that seems still relevant is

> I can't see who asked a question and when, nor anything about the voting process other than the up count (Possibly privacy issues there, I guess). Everything in the main chat tab has this info.

which I personally think is intentional. It's not so much of a privacy issue as an intentional simplification/anonymization

**Closed by raphaelm** 2021-12-19 16:23 UTC
