### ISSUE TITLE
Websocket not working (error "socket closed" on page load)

### ISSUE THREAD

**Issue by ghoeffner** [venueless/venueless#188] opened 2021-02-02 18:08 UTC
Hey everyone,

while I understand that you probably can't support every individual combination of webservers and venueless, I was hoping that someone could point me in the right direction of what's going wrong or giving me pointers on how to further debug this issue.

I originally opened a issue with caddy, because I thought I misconfigured something. Turns out that caddy forwards all headers by default and it should work with venueless (pretty much) out of the box, find my caddy config & information over here: https://caddy.community/t/config-for-venueless-reverse-proxy-giving-me-socket-timeout-errors/11342/2

Thanks for your help in advance!

**Comment by raphaelm** [comment] 2021-02-02 18:19
Uh, indeed I have never used caddy in my life and I'm not sure I can spend the time looking into this :( We run venueless behind nginx and haproxy, which doesn't require anything too special.

**Comment by ghoeffner** [comment] 2021-02-02 18:22
Thanks for the swift response @raphaelm. Is there any pointers you can give me in terms of logs that I can look into or something else? Have you guys ever had this "socket closed" error before? (I searched the github issues, but there was nothing).

**Comment by raphaelm** [comment] 2021-02-02 18:32
Nah, "socket closed" just means the websocket (which should normally stay active for the whole usage duration) has been closed by the server or something in between. I don't think it's related to HTTP headers, sounds more like a problem with websocket or timeout configuration in caddy.

**Comment by raphaelm** [comment] 2021-02-03 07:18
Hi @francislavoie, I honestly don't know. Venueless only logs errors, it's worth looking into the log file in the data directory, but of that's clean I don't really have any good idea short of spinning up wireshark...

**Comment by ghoeffner** [comment] 2021-02-03 09:57
@raphaelm There is indeed an error popping up at /data/logs/venueless.log that seems related to websockets. But I can't get to trigger it right now (maybe there is a long timeout or something so it gets written to the log delayed?)

```
2021-02-02 12:12:05,147 ERROR 139850972317440 asyncio query Task was destroyed but it is pending!
task: <Task pending name='Task-2770' coro=<WebSocketServerProtocol.handler() done, defined at /usr/local/lib/python3.8/site-packages/websockets/server.py:118> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f3196e8a490>()]>>
2021-02-02 12:12:09,468 ERROR 139851287705408 asyncio tasks Task was destroyed but it is pending!
task: <Task pending name='Task-1822' coro=<WebSocketServerProtocol.handler() done, defined at /usr/local/lib/python3.8/site-packages/websockets/server.py:118> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f3196e37070>()]>>
2021-02-02 12:12:09,469 ERROR 139851287705408 asyncio tasks Task was destroyed but it is pending!
task: <Task pending name='Task-1825' coro=<WebSocketServerProtocol.handler() done, defined at /usr/local/lib/python3.8/site-packages/websockets/server.py:118> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f3196e5c5e0>()]>>
2021-02-02 12:12:09,469 ERROR 139851287705408 asyncio tasks Task was destroyed but it is pending!
task: <Task pending name='Task-1827' coro=<WebSocketServerProtocol.handler() done, defined at /usr/local/lib/python3.8/site-packages/websockets/server.py:118> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f3196d7d4f0>()]>>
2021-02-02 12:12:09,469 ERROR 139851287705408 asyncio tasks Task was destroyed but it is pending!
task: <Task pending name='Task-1830' coro=<WebSocketServerProtocol.handler() done, defined at /usr/local/lib/python3.8/site-packages/websockets/server.py:118> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f3196e1ca60>()]>>
2021-02-02 12:12:09,470 ERROR 139851287705408 asyncio tasks Task was destroyed but it is pending!
task: <Task pending name='Task-1832' coro=<WebSocketServerProtocol.handler() done, defined at /usr/local/lib/python3.8/site-packages/websockets/server.py:118> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f3196e3e070>()]>>
2021-02-02 12:12:10,562 ERROR 139851287705408 asyncio protocol Task was destroyed but it is pending!
task: <Task pending name='Task-2069' coro=<WebSocketServerProtocol.handler() done, defined at /usr/local/lib/python3.8/site-packages/websockets/server.py:118> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f3196e05eb0>()]>>
2021-02-02 12:12:10,562 ERROR 139851287705408 asyncio protocol Task was destroyed but it is pending!
task: <Task pending name='Task-2071' coro=<WebSocketServerProtocol.handler() done, defined at /usr/local/lib/python3.8/site-packages/websockets/server.py:118> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f3196e30d90>()]>>
2021-02-02 12:12:10,562 ERROR 139851287705408 asyncio protocol Task was destroyed but it is pending!
task: <Task pending name='Task-2073' coro=<WebSocketServerProtocol.handler() done, defined at /usr/local/lib/python3.8/site-packages/websockets/server.py:118> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f3196e0ed00>()]>>
2021-02-02 12:12:48,018 ERROR 139850972317440 asyncio query Task was destroyed but it is pending!
task: <Task pending name='Task-1922' coro=<WebSocketServerProtocol.handler() running at /usr/local/lib/python3.8/site-packages/websockets/server.py:130> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f3196e5c2b0>()]>>
2021-02-02 12:12:48,018 ERROR 139850972317440 asyncio query Task was destroyed but it is pending!
task: <Task pending name='Task-1962' coro=<WebSocketServerProtocol.handler() running at /usr/local/lib/python3.8/site-packages/websockets/server.py:130> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f3196e30df0>()]>>
2021-02-02 12:14:52,015 ERROR 139850972317440 asyncio query Task was destroyed but it is pending!
task: <Task pending name='Task-2723' coro=<WebSocketServerProtocol.handler() running at /usr/local/lib/python3.8/site-packages/websockets/server.py:130> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f3196deec40>()]>>
2021-02-02 12:14:52,015 ERROR 139850972317440 asyncio query Task was destroyed but it is pending!
task: <Task pending name='Task-2743' coro=<WebSocketServerProtocol.handler() running at /usr/local/lib/python3.8/site-packages/websockets/server.py:130> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f3196e61940>()]>>
2021-02-02 12:14:52,016 ERROR 139850972317440 asyncio query Task was destroyed but it is pending!
task: <Task pending name='Task-2766' coro=<WebSocketServerProtocol.handler() running at /usr/local/lib/python3.8/site-packages/websockets/server.py:130> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f3196f9e7c0>()]>>
2021-02-02 12:15:16,010 ERROR 139850972317440 asyncio query Task was destroyed but it is pending!
task: <Task pending name='Task-1820' coro=<WebSocketServerProtocol.handler() running at /usr/local/lib/python3.8/site-packages/websockets/server.py:130> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f3196ede670>()]>>
```

There is more in that log but it seems repetative.

**Comment by ghoeffner** [comment] 2021-02-03 23:16
Now it's getting interesting @raphaelm, I am seeing the exact same thing when using Nginx. I performed the installation as shown in the docs. Not sure where to go from here :(

**Comment by raphaelm** [comment] 2021-02-04 08:36
Huh. And these are the only errors in the sever log?

**Comment by raphaelm** [comment] 2021-02-04 08:38
Can you check if `journalctl -u venueless.service` shows something more interesting?

**Comment by ghoeffner** [comment] 2021-02-04 08:57
venueless log:

```
-- Logs begin at Wed 2020-03-18 23:16:07 CET, end at Thu 2021-02-04 09:54:04 CET. --
Feb 02 11:20:46 x systemd[1]: Starting venueless...
Feb 02 11:20:46 x docker[24223]: WARNING: Error loading config file: .dockercfg: $HOME is not defined
Feb 02 11:20:46 x docker[24223]: Error response from daemon: Cannot kill container: venueless.service: No such container: venueless.service
Feb 02 11:20:46 x docker[24240]: WARNING: Error loading config file: .dockercfg: $HOME is not defined
Feb 02 11:20:46 x docker[24240]: Error: No such container: venueless.service
Feb 02 11:20:46 x systemd[1]: Started venueless.
Feb 02 11:20:47 x docker[24248]: WARNING: Error loading config file: .dockercfg: $HOME is not defined
Feb 02 11:20:51 x docker[24248]: 2021-02-02 11:20:51,625 INFO 140202981734208 matplotlib.font_manager font_manager Generating new fontManager, this may take some time...
Feb 02 11:21:03 x docker[24248]: System check identified some issues:
Feb 02 11:21:03 x docker[24248]: WARNINGS:
Feb 02 11:21:03 x docker[24248]: core.AuditLog.data: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) w
Feb 02 11:21:03 x docker[24248]:         HINT: Use django.db.models.JSONField instead.
Feb 02 11:21:03 x docker[24248]: core.ChatEvent.content: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migration
Feb 02 11:21:03 x docker[24248]:         HINT: Use django.db.models.JSONField instead.
Feb 02 11:21:03 x docker[24248]: core.Room.module_config: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migratio
Feb 02 11:21:03 x docker[24248]:         HINT: Use django.db.models.JSONField instead.
Feb 02 11:21:03 x docker[24248]: core.Room.schedule_data: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migratio
Feb 02 11:21:03 x docker[24248]:         HINT: Use django.db.models.JSONField instead.
Feb 02 11:21:03 x docker[24248]: core.Room.trait_grants: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migration
Feb 02 11:21:03 x docker[24248]:         HINT: Use django.db.models.JSONField instead.
Feb 02 11:21:03 x docker[24248]: core.User.profile: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) wi
Feb 02 11:21:03 x docker[24248]:         HINT: Use django.db.models.JSONField instead.
Feb 02 11:21:03 x docker[24248]: core.World.config: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) wi
Feb 02 11:21:03 x docker[24248]:         HINT: Use django.db.models.JSONField instead.
Feb 02 11:21:03 x docker[24248]: core.World.feature_flags: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrati
Feb 02 11:21:03 x docker[24248]:         HINT: Use django.db.models.JSONField instead.
Feb 02 11:21:03 x docker[24248]: core.World.roles: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) wil
Feb 02 11:21:03 x docker[24248]:         HINT: Use django.db.models.JSONField instead.
Feb 02 11:21:03 x docker[24248]: core.World.trait_grants: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migratio
Feb 02 11:21:03 x docker[24248]:         HINT: Use django.db.models.JSONField instead.
Feb 02 11:21:03 x docker[24248]: Operations to perform:
Feb 02 11:21:03 x docker[24248]:   Apply all migrations: contenttypes, core, storage
Feb 02 11:21:03 x docker[24248]: Running migrations:
Feb 02 11:21:03 x docker[24248]:   Applying contenttypes.0001_initial... OK
Feb 02 11:21:03 x docker[24248]:   Applying contenttypes.0002_remove_content_type_name... OK
Feb 02 11:21:03 x docker[24248]:   Applying core.0001_initial... OK
Feb 02 11:21:03 x docker[24248]:   Applying core.0002_world_domain... OK
Feb 02 11:21:03 x docker[24248]:   Applying core.0003_auto_20200430_2018... OK
Feb 02 11:21:03 x docker[24248]:   Applying core.0004_auto_20200516_1225... OK
Feb 02 11:21:03 x docker[24248]:   Applying core.0005_reaction... OK
Feb 02 11:21:03 x docker[24248]:   Applying core.0006_auto_20200520_2203... OK
Feb 02 11:21:03 x docker[24248]:   Applying core.0007_reaction_datetime... OK
Feb 02 11:21:03 x docker[24248]:   Applying core.0008_auto_20200526_1258... OK
Feb 02 11:21:03 x docker[24248]:   Applying core.0009_world_locale... OK
Feb 02 11:21:03 x docker[24248]:   Applying core.0010_user_moderation_state... OK
```

Found another (potentially related) error in the log (probably appeared after starting the docker container):

```
2021-02-04 00:19:42,200 INFO 140192810493760 matplotlib.font_manager font_manager Generating new fontManager, this may take some time...
2021-02-04 00:19:55,486 WARNING 140254838769472 websockets.server server Error in opening handshake
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/websockets/server.py", line 130, in handler
    path = await self.handshake(
  File "/usr/local/lib/python3.8/site-packages/websockets/server.py", line 584, in handshake
    self.write_http_response(http.HTTPStatus.SWITCHING_PROTOCOLS, response_headers)
  File "/usr/local/lib/python3.8/site-packages/websockets/server.py", line 264, in write_http_response
    self.transport.write(response.encode())
  File "uvloop/handles/stream.pyx", line 673, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <UnixTransport closed=True reading=False 0x7f8f97920380>; the handler is closed
2021-02-04 00:19:55,503 WARNING 140254838769472 websockets.server server Error in opening handshake
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/websockets/server.py", line 130, in handler
    path = await self.handshake(
  File "/usr/local/lib/python3.8/site-packages/websockets/server.py", line 584, in handshake
    self.write_http_response(http.HTTPStatus.SWITCHING_PROTOCOLS, response_headers)
  File "/usr/local/lib/python3.8/site-packages/websockets/server.py", line 264, in write_http_response
    self.transport.write(response.encode())
  File "uvloop/handles/stream.pyx", line 673, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <UnixTransport closed=True reading=False 0x7f8f8d681a00>; the handler is closed
```

**Comment by raphaelm** [comment] 2021-02-04 09:08
> venueless log:

This looks like just the first page from when you first ever started it. The more recent logs would be btter :)

**Comment by ghoeffner** [comment] 2021-02-04 09:12
Sorry, it's early ;) This one seems to be from the restart I did last night:

```
Feb 04 00:19:35 x systemd[1]: Starting venueless...
Feb 04 00:19:35 x docker[10362]: WARNING: Error loading config file: .dockercfg: $HOME is not defined
Feb 04 00:19:35 x docker[10362]: Error response from daemon: Cannot kill container: venueless.service: Container 00cb72449b6af504f478f32c971afeadafc762f6c1836141ccb9f4e971ff
Feb 04 00:19:35 x docker[10383]: WARNING: Error loading config file: .dockercfg: $HOME is not defined
Feb 04 00:19:35 x docker[10383]: venueless.service
Feb 04 00:19:35 x systemd[1]: Started venueless.
Feb 04 00:19:35 x docker[10391]: WARNING: Error loading config file: .dockercfg: $HOME is not defined
Feb 04 00:19:42 x docker[10391]: 2021-02-04 00:19:42,200 INFO 140192810493760 matplotlib.font_manager font_manager Generating new fontManager, this may take some time...
Feb 04 00:19:44 x docker[10391]: System check identified some issues:
Feb 04 00:19:44 x docker[10391]: WARNINGS:
Feb 04 00:19:44 x docker[10391]: core.AuditLog.data: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) w
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: core.ChatEvent.content: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migration
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: core.Room.module_config: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migratio
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: core.Room.schedule_data: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migratio
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: core.Room.trait_grants: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migration
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: core.User.profile: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) wi
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: core.World.config: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) wi
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: core.World.feature_flags: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrati
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: core.World.roles: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) wil
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: core.World.trait_grants: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migratio
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: Operations to perform:
Feb 04 00:19:44 x docker[10391]:   Apply all migrations: contenttypes, core, storage
Feb 04 00:19:44 x docker[10391]: Running migrations:
Feb 04 00:19:44 x docker[10391]:   No migrations to apply.
Feb 04 00:19:45 x docker[10391]: 2021-02-03 23:19:45,589 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  I
Feb 04 00:19:45 x docker[10391]: 2021-02-03 23:19:45,589 WARN No file matches via include "/etc/supervisord-*.conf"
Feb 04 00:19:45 x docker[10391]: 2021-02-03 23:19:45,617 INFO RPC interface 'supervisor' initialized
Feb 04 00:19:45 x docker[10391]: 2021-02-03 23:19:45,617 CRIT Server 'unix_http_server' running without any HTTP authentication checking
Feb 04 00:19:45 x docker[10391]: 2021-02-03 23:19:45,618 INFO supervisord started with pid 14
Feb 04 00:19:46 x docker[10391]: 2021-02-03 23:19:46,621 INFO spawned: 'celery' with pid 17
Feb 04 00:19:46 x docker[10391]: 2021-02-03 23:19:46,625 INFO spawned: 'webserver' with pid 18
Feb 04 00:19:46 x docker[10391]: 2021-02-03 23:19:46,629 INFO spawned: 'nginx' with pid 19
Feb 04 00:19:47 x docker[10391]: 2021-02-03 23:19:47,657 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Feb 04 00:19:47 x docker[10391]: 2021-02-03 23:19:47,658 INFO success: webserver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Feb 04 00:19:47 x docker[10391]: 2021-02-03 23:19:47,658 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)Feb 04 00:19:35 x systemd[1]: Starting venueless...
Feb 04 00:19:35 x docker[10362]: WARNING: Error loading config file: .dockercfg: $HOME is not defined
Feb 04 00:19:35 x docker[10362]: Error response from daemon: Cannot kill container: venueless.service: Container 00cb72449b6af504f478f32c971afeadafc762f6c1836141ccb9f4e971ff
Feb 04 00:19:35 x docker[10383]: WARNING: Error loading config file: .dockercfg: $HOME is not defined
Feb 04 00:19:35 x docker[10383]: venueless.service
Feb 04 00:19:35 x systemd[1]: Started venueless.
Feb 04 00:19:35 x docker[10391]: WARNING: Error loading config file: .dockercfg: $HOME is not defined
Feb 04 00:19:42 x docker[10391]: 2021-02-04 00:19:42,200 INFO 140192810493760 matplotlib.font_manager font_manager Generating new fontManager, this may take some time...
Feb 04 00:19:44 x docker[10391]: System check identified some issues:
Feb 04 00:19:44 x docker[10391]: WARNINGS:
Feb 04 00:19:44 x docker[10391]: core.AuditLog.data: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) w
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: core.ChatEvent.content: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migration
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: core.Room.module_config: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migratio
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: core.Room.schedule_data: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migratio
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: core.Room.trait_grants: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migration
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: core.User.profile: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) wi
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: core.World.config: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) wi
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: core.World.feature_flags: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrati
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: core.World.roles: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) wil
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: core.World.trait_grants: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migratio
Feb 04 00:19:44 x docker[10391]:         HINT: Use django.db.models.JSONField instead.
Feb 04 00:19:44 x docker[10391]: Operations to perform:
Feb 04 00:19:44 x docker[10391]:   Apply all migrations: contenttypes, core, storage
Feb 04 00:19:44 x docker[10391]: Running migrations:
Feb 04 00:19:44 x docker[10391]:   No migrations to apply.
Feb 04 00:19:45 x docker[10391]: 2021-02-03 23:19:45,589 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  I
Feb 04 00:19:45 x docker[10391]: 2021-02-03 23:19:45,589 WARN No file matches via include "/etc/supervisord-*.conf"
Feb 04 00:19:45 x docker[10391]: 2021-02-03 23:19:45,617 INFO RPC interface 'supervisor' initialized
Feb 04 00:19:45 x docker[10391]: 2021-02-03 23:19:45,617 CRIT Server 'unix_http_server' running without any HTTP authentication checking
Feb 04 00:19:45 x docker[10391]: 2021-02-03 23:19:45,618 INFO supervisord started with pid 14
Feb 04 00:19:46 x docker[10391]: 2021-02-03 23:19:46,621 INFO spawned: 'celery' with pid 17
Feb 04 00:19:46 x docker[10391]: 2021-02-03 23:19:46,625 INFO spawned: 'webserver' with pid 18
Feb 04 00:19:46 x docker[10391]: 2021-02-03 23:19:46,629 INFO spawned: 'nginx' with pid 19
Feb 04 00:19:47 x docker[10391]: 2021-02-03 23:19:47,657 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Feb 04 00:19:47 x docker[10391]: 2021-02-03 23:19:47,658 INFO success: webserver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Feb 04 00:19:47 x docker[10391]: 2021-02-03 23:19:47,658 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by francislavoie** [comment] 2021-02-04 11:27
> Found another (potentially related) error in the /data/logs/venueless.log (probably appeared after starting the docker container):

That websocket error looks like exactly the thing. The websocket being closed early during upgrade.

**Comment by raphaelm** [comment] 2021-02-04 11:30
Well yeah, it confirms *that* the websocket is closed, but it gives no indication as to *why* :D

**Comment by ghoeffner** [comment] 2021-02-04 11:33
Is there anything that I can provide that could help figuring out?

**Comment by francislavoie** [comment] 2021-02-04 11:36
Would it be possible to try again on a fresh VM? To reduce the variables.

**Comment by ghoeffner** [comment] 2021-02-04 11:47
I am not a docker expert, but this should do, right?

```
root@x:~# systemctl stop venueless.service
root@x:~# systemctl status venueless.service | grep stop
  Process: 8623 ExecStop=/usr/bin/docker stop venueless.service (code=exited, status=0/SUCCESS)
Feb 04 12:43:12 x docker[10391]: 2021-02-04 11:43:12,124 INFO stopped: nginx (exit status 0)
Feb 04 12:43:16 x docker[10391]: 2021-02-04 11:43:16,451 INFO stopped: webserver (exit status 0)
Feb 04 12:43:21 x docker[10391]: 2021-02-04 11:43:21,032 INFO stopped: celery (exit status 0)
root@x:~# docker rm venueless.service
venueless.service
root@x:~# docker ps -a
CONTAINER ID   IMAGE                      COMMAND                  CREATED        STATUS                 PORTS                                            NAMES

root@x:~# docker pull venueless/venueless:latest
latest: Pulling from venueless/venueless
Digest: sha256:1d1cf7bd60c75ca66993fd0b1d911a227d47553dde7710242144a5f642685eee
Status: Image is up to date for venueless/venueless:latest
docker.io/venueless/venueless:latest
root@x:~# systemctl start venueless.service
root@x:~# systemctl status venueless.service
● venueless.service - venueless
   Loaded: loaded (/etc/systemd/system/venueless.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2021-02-04 12:45:41 CET; 4s ago
  Process: 8623 ExecStop=/usr/bin/docker stop venueless.service (code=exited, status=0/SUCCESS)
  Process: 9019 ExecStartPre=/usr/bin/docker rm venueless.service (code=exited, status=1/FAILURE)
  Process: 8997 ExecStartPre=/usr/bin/docker kill venueless.service (code=exited, status=1/FAILURE)
 Main PID: 9026 (docker)
    Tasks: 10 (limit: 2338)
   CGroup: /system.slice/venueless.service
           └─9026 /usr/bin/docker run --name venueless.service -p 8002:80 -v /var/venueless-data:/data -v /etc/venueless:/etc/venueless --sysctl net.core.somaxconn=4096 venueless/

Feb 04 12:45:41 x systemd[1]: Starting venueless...
Feb 04 12:45:41 x docker[8997]: WARNING: Error loading config file: .dockercfg: $HOME is not defined
Feb 04 12:45:41 x docker[8997]: Error response from daemon: Cannot kill container: venueless.service: No such container: venueless.service
Feb 04 12:45:41 x docker[9019]: WARNING: Error loading config file: .dockercfg: $HOME is not defined
Feb 04 12:45:41 x docker[9019]: Error: No such container: venueless.service
Feb 04 12:45:41 x systemd[1]: Started venueless.
Feb 04 12:45:41 x docker[9026]: WARNING: Error loading config file: .dockercfg: $HOME is not defined
Feb 04 12:45:46 x docker[9026]: 2021-02-04 12:45:46,264 INFO 139674679621440 matplotlib.font_manager font_manager Generating new fontManager, this may take some time...
```

Unfortunately that didn't resolve the issue

**Comment by raphaelm** [comment] 2021-02-04 22:29
Have you tried what happens if you point a browser to the port exposed by the docker container directly, ie with neither caddy nor nginx in between?

I'm really baffled by this, because if venueless is closing connections right away, I don't get why there's no helpful exception in the log

**Comment by ghoeffner** [comment] 2021-02-04 22:40
Unfortunately there is no easy way of doing this, as the server in question is only connected via an internal network and I can only access it using a jumphost... but I will give it some thought on how to connect to the docker directly. There is probably a way that involves tunneling the ports :P

**Comment by ghoeffner** [comment] 2021-02-04 23:08
@raphaelm Alright, so with a bit of ssh tunneling fun I was able to test it and the result is the same, unfortunately.
![ubodrvanew84](https://user-images.githubusercontent.com/1123412/106966761-405adb80-6746-11eb-9e19-cc084d102fd8.gif)

**Comment by raphaelm** [comment] 2021-02-05 09:57
So to figure out if this is a problem with your setup or venueless, I grabbed a blank hetzner cloud server running debian 10 and tried following the tutorial exactly:

```
# apt update
# apt install redis-server postgresql nginx curl apt-transport-https ca-certificates  software-properties-common vim
# curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
# add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"
# apt update
# apt install docker-ce docker-ce-cli containerd.io
# mkdir /var/venueless-data
# chown -R 15371:15371 /var/venueless-data
# sudo -u postgres createuser -P venueless
# sudo -u postgres createdb -O venueless venueless
# sed -i "s/.*listen_address.*/listen_addresses = 'localhost,172.17.0.1'/" /etc/postgresql/11/main/postgresql.conf
# echo "host    venueless          venueless          172.17.0.1/16           md5" >> /etc/postgresql/11/main/pg_hba.conf
# systemctl restart postgresql
# sed -i "s/^bind .*/bind 172.17.0.1 127.0.0.1/" /etc/redis/redis.conf
# systemctl restart redis-server
# mkdir /etc/venueless
# touch /etc/venueless/venueless.cfg
# chown -R 15371:15371 /etc/venueless/
# chmod 0700 /etc/venueless/venueless.cfg
# cat <<EOF >/etc/venueless/venueless.cfg
[database]
backend=postgresql
name=venueless
user=venueless
password=venueless
host=172.17.0.1

[redis]
host=172.17.0.1
EOF
# docker pull venueless/venueless:latest
# cat <<EOF >/etc/systemd/system/venueless.service
[Unit]
Description=venueless
After=docker.service
Requires=docker.service

[Service]
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill %n
ExecStartPre=-/usr/bin/docker rm %n
ExecStart=/usr/bin/docker run --name %n -p 8002:80 \
    -v /var/venueless-data:/data \
    -v /etc/venueless:/etc/venueless \
    --sysctl net.core.somaxconn=4096 \
    venueless/venueless:latest all
ExecStop=/usr/bin/docker stop %n

[Install]
WantedBy=multi-user.target
EOF
# systemctl daemon-reload
# systemctl enable venueless
# systemctl start venueless
# docker exec -it venueless.service venueless create_world
Enter the internal ID for the new world (alphanumeric): demo
Enter the title for the new world: demo
Enter the domain of the new world (e.g. myevent.example.org): 135.181.80.52:8002
World created.
Default API keys: [{'issuer': 'any', 'audience': 'venueless', 'secret': 'zvB7hI28vbrI7KtsRnJ1TZBSN3DvYdoy9VoJGLI1ouHQP5VtRG3U6AgKJ9YOqKNU'}]
```

Then, I pointed my browser to http://135.181.80.52:8002/, which did not work and looked similar to your video. This was caused by venueless pointing the browser to ``wss://135.181.80.52/ws/demo/`` as a websocket target, while ``ws://135.181.80.52:8002/ws/demo/`` would have been correct.

Commit 21fc3ccd829f39e31c1a42001e10938c4ce987e4 now fixes the missing port and commit 0c79a9ab7adae8a3645b22ea27071c2798c639a4 adds a config option for the websocket protocol. The new docker container isn't yet on docker hub, but with rebuilding it manually and setting

```
[websocket]
protocol=ws
```

in venueless.cfg, everything works fine for me.

**Closed by raphaelm** 2021-02-05 09:57 UTC

**Comment by ghoeffner** [comment] 2021-02-05 10:14
With the live installation I was trying on the default https port, but updating as we speak and testing this ;)

**Comment by ghoeffner** [comment] 2021-02-05 10:57
Your setup looks exactly like mine, honestly. Also on the latest version of everything - docker etc (just checked). 
Just created a new world and it's the same issue even when accessing it directly with the tunnel:
![image](https://user-images.githubusercontent.com/1123412/107025098-3918e980-67a9-11eb-9595-d432b6df7d54.png)

**Comment by raphaelm** [comment] 2021-02-05 11:02
Can you look if there are any messages going through the websocket before it closes?

Can you check if redis works properly (issue a ``KEYS *`` maybe, there should be some data in there)

**Comment by ghoeffner** [comment] 2021-02-05 11:10
Can I somehow check redis from within the docker container? That IS a good pointer, as I am using redis WITH password auth, which seems quiet non-standard...

**Comment by raphaelm** [comment] 2021-02-05 11:32
We also use it with redis auth in production, just skipped it for the test. If there's a ``venueless:asgi:*`` key I'm pretty sure it works, though

**Comment by raphaelm** [comment] 2021-02-05 11:53
As much as I like to help you, I'm really running out of both time and ideas here… can you try on a new server with exactly the same steps I posted and then work your way to your setup from there? :D

**Comment by ghoeffner** [comment] 2021-02-05 11:55
Sure thing, I guess I'll take a small break here as well 😥 😉
Thanks for the help this far.
